/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpcgen_user_registry.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_out_svr_response *
register_user_proc_1(rpc_in_login_details *argp, CLIENT *clnt)
{
	static rpc_out_svr_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTER_USER_PROC,
		(xdrproc_t) xdr_rpc_in_login_details, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_out_svr_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rpc_out_svr_response *
user_login_proc_1(rpc_in_login_details *argp, CLIENT *clnt)
{
	static rpc_out_svr_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, USER_LOGIN_PROC,
		(xdrproc_t) xdr_rpc_in_login_details, (caddr_t) argp,
		(xdrproc_t) xdr_rpc_out_svr_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
