/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcgen_user_registry.h"

bool_t
xdr_rpc_in_login_details (XDR *xdrs, rpc_in_login_details *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->username, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_out_svr_response (XDR *xdrs, rpc_out_svr_response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->response_code))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->response_msg, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->num_users))
		 return FALSE;
	return TRUE;
}
