/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCGEN_USER_REGISTRY_H_RPCGEN
#define _RPCGEN_USER_REGISTRY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rpc_in_login_details {
	char username[256];
	char password[256];
};
typedef struct rpc_in_login_details rpc_in_login_details;

struct rpc_out_svr_response {
	long response_code;
	char response_msg[256];
	long num_users;
};
typedef struct rpc_out_svr_response rpc_out_svr_response;

#define REGISTER_USER_PROG 0x13451111
#define REGISTER_USER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER_USER_PROC 1
extern  rpc_out_svr_response * register_user_proc_1(rpc_in_login_details *, CLIENT *);
extern  rpc_out_svr_response * register_user_proc_1_svc(rpc_in_login_details *, struct svc_req *);
#define USER_LOGIN_PROC 2
extern  rpc_out_svr_response * user_login_proc_1(rpc_in_login_details *, CLIENT *);
extern  rpc_out_svr_response * user_login_proc_1_svc(rpc_in_login_details *, struct svc_req *);
extern int register_user_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER_USER_PROC 1
extern  rpc_out_svr_response * register_user_proc_1();
extern  rpc_out_svr_response * register_user_proc_1_svc();
#define USER_LOGIN_PROC 2
extern  rpc_out_svr_response * user_login_proc_1();
extern  rpc_out_svr_response * user_login_proc_1_svc();
extern int register_user_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_in_login_details (XDR *, rpc_in_login_details*);
extern  bool_t xdr_rpc_out_svr_response (XDR *, rpc_out_svr_response*);

#else /* K&R C */
extern bool_t xdr_rpc_in_login_details ();
extern bool_t xdr_rpc_out_svr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCGEN_USER_REGISTRY_H_RPCGEN */
